name: OpenWrt-IPK-Builder

on: 
  workflow_dispatch:
    inputs:
      Model:
        description: '选择设备（自动解析架构）'
        required: true
        default: '迷你主机'
        type: choice
        options: ['迷你主机', '普通PC', 'Proxmox VE虚拟机', 'VMware虚拟机', '小米路由器4A千兆版', 'Xiaomi R4A', 'Redmi AX6', 'Redmi AX6000', '小米AX3600', 'Xiaomi AX9000', 'ASUS RT-ACRH17', 'ASUS RT-AC58U', 'ASUS RT-AX86U', 'ASUS RT-AX88U', 'Netgear R7800', 'Netgear XR500', 'Netgear WAX202', 'Linksys WRT1900ACS', 'Linksys WRT3200ACM', 'Linksys EA7500v2', 'GL.iNet MT1300', 'GL.iNet AX1800', '斐讯K3', 'Newifi D2', '极路由4 HC5962', 'Raspberry Pi 4B']
      Package:
        description: '输入包名 (例如: luci-app-adguardhome)'
        required: false
        type: string

env:
  TZ: Asia/Shanghai

jobs:
  matrix:
    runs-on: ubuntu-latest
    if: github.event.repository.owner.id == github.event.sender.id || !github.event.sender.id
    outputs:
      matrix: ${{ steps.set-matrix.outputs.matrix }}
      repo_url: ${{ steps.set-matrix.outputs.repo_url }}
    
    steps:
      - name: 检出代码
        uses: actions/checkout@v4

      - name: 解析设备架构
        id: parse-model
        run: |
          MODEL_INPUT="${{ github.event.inputs.Model }}"
          echo "model_name=$MODEL_INPUT" >> $GITHUB_ENV
          
          if [ ! -f "scripts/Models" ]; then
            echo "::error::架构映射文件 scripts/Models 不存在"
            exit 1
          fi
          
          FOUND_ARCH=""
          while IFS= read -r line || [[ -n "$line" ]]; do
            line_clean=$(echo "$line" | sed -e 's/#.*//' -e 's/^[[:space:]]*//' -e 's/[[:space:]]*$//')
            [ -z "$line_clean" ] && continue
            
            IFS=':' read -ra parts <<< "$line_clean"
            if [ ${#parts[@]} -ne 2 ]; then
              continue
            fi
            
            devices=$(echo "${parts}" | tr ',' '\n' | sed 's/^[[:space:]]*//;s/[[:space:]]*$//')
            target_arch=$(echo "${parts}" | sed 's/^[[:space:]]*//;s/[[:space:]]*$//')
            
            while read -r device; do
              if [ "$device" == "$MODEL_INPUT" ]; then
                if [ -n "$FOUND_ARCH" ]; then
                  echo "::error::设备 '$MODEL_INPUT' 在多个架构中定义"
                  exit 1
                fi
                FOUND_ARCH="$target_arch"
              fi
            done <<< "$devices"
          done < scripts/Models
          
          if [ -z "$FOUND_ARCH" ]; then
            echo "::error::未找到设备 '$MODEL_INPUT' 对应的架构"
            exit 1
          fi
          echo "arch=$FOUND_ARCH" >> $GITHUB_OUTPUT

      - name: 构建包矩阵
        id: set-matrix
        env:
          TARGET_ARCH: ${{ steps.parse-model.outputs.arch }}
        run: |
          PACKAGE_INPUT="${{ github.event.inputs.Package }}"
          REPO_URL="https://github.com/somemoo/OpenWrt-packages"
          BRANCH="lede"
          PKG_ARRAY=()
          USE_BUILD_FILE=false

          if [ -n "$PACKAGE_INPUT" ]; then
            IFS=',; ' read -ra PKG_ARRAY <<< "$PACKAGE_INPUT"
          elif [ -f "Build-IPK" ]; then
            declare -a tmp_pkgs
            while IFS= read -r line; do
              if [[ "$line" =~ ^[[:space:]]*# ]] || [[ -z "${line// }" ]]; then
                continue
              fi
              IFS=',; ' read -ra pkgs <<< "$line"
              for pkg in "${pkgs[@]}"; do
                clean_pkg=$(echo "$pkg" | xargs)
                [ -n "$clean_pkg" ] && tmp_pkgs+=("$clean_pkg")
              done
            done < Build-IPK
            if [ ${#tmp_pkgs[@]} -gt 0 ]; then
              PKG_ARRAY=("${tmp_pkgs[@]}")
              USE_BUILD_FILE=true
            fi
          fi

          git clone -b $BRANCH --single-branch $REPO_URL OpenWrt-packages
          cd OpenWrt-packages

          filtered_pkgs=()
          missing_pkgs=()
          for pkg in "${PKG_ARRAY[@]}"; do
            if [ -d "$pkg" ]; then
              filtered_pkgs+=("$pkg")
            else
              missing_pkgs+=("$pkg")
            fi
          done

          if [ ${#missing_pkgs[@]} -gt 0 ]; then
            cd ../..
            REPO_URL="https://github.com/kiddin9/kwrt-packages"
            BRANCH="main"
            git clone -b $BRANCH --single-branch $REPO_URL OpenWrt-packages-alt
            cd OpenWrt-packages-alt
            for pkg in "${missing_pkgs[@]}"; do
              if [ -d "$pkg" ]; then
                filtered_pkgs+=("$pkg")
              fi
            done
            cd ..
          fi

          PKG_ARRAY=("${filtered_pkgs[@]}")
          if [ ${#PKG_ARRAY[@]} -eq 0 ]; then
            echo "::error::所有包均不存在，无法构建"
            exit 1
          fi

          targets_json=$(jq -c -n \
            --argjson arr "$(printf '%s\n' "${PKG_ARRAY[@]}" | jq -R . | jq -s .)" \
            --arg arch "$TARGET_ARCH" \
            '[$arch as $a | $arr[] | {target: ., arch: $a}]')
          echo "matrix=$targets_json" >> $GITHUB_OUTPUT
          echo "repo_url=$REPO_URL" >> $GITHUB_OUTPUT

  build:
    name: 构建 ${{ matrix.target }} (${{ matrix.arch }})
    runs-on: ubuntu-latest
    needs: matrix
    strategy:
      matrix:
        include: ${{ fromJson(needs.matrix.outputs.matrix) }}
      fail-fast: false
    env:
      REPO_URL: ${{ needs.matrix.outputs.repo_url }}

    steps:
      - name: 设置变量
        id: ENV
        run: |
          echo "date=$(date +'%m.%d')" >> $GITHUB_ENV
          echo "arch_path=${{ needs.matrix.jobs.parse-model.outputs.arch }}" >> $GITHUB_ENV
          echo "model_name=${{ env.model_name }}" >> $GITHUB_ENV

      - name: 准备SDK
        run: |
          SDK_URL1="https://downloads.immortalwrt.org/releases/24.10-SNAPSHOT/targets/${{ matrix.arch }}/immortalwrt-sdk-24.10-SNAPSHOT-$(echo ${{ matrix.arch }} | tr '/' '-')_gcc-13.3.0_musl.Linux-x86_64.tar.zst"
          SDK_URL2="https://downloads.immortalwrt.org/releases/24.10-SNAPSHOT/targets/${{ matrix.arch }}/immortalwrt-sdk-24.10-SNAPSHOT-$(echo ${{ matrix.arch }} | tr '/' '-')_gcc-13.3.0_musl_eabi.Linux-x86_64.tar.zst"
          wget --spider -q "$SDK_URL1" && wget "$SDK_URL1" || wget "$SDK_URL2"
          mkdir OpenWrt-$(echo ${{ matrix.arch }} | tr '/' '-') && tar -I 'zstd -d' -xf immortalwrt-*.tar.zst -C OpenWrt-$(echo ${{ matrix.arch }} | tr '/' '-') --strip-components 1 && rm immortalwrt-*.tar.zst

      - name: 克隆项目
        run: |
          shopt -s extglob
          cp -rf App/. OpenWrt-$(echo ${{ matrix.arch }} | tr '/' '-')/
          cd OpenWrt-$(echo ${{ matrix.arch }} | tr '/' '-')
          ./scripts/feeds update -a
          rm -Rf feeds/luci/{applications,collections,protocols,themes,libs,docs,contrib}
          rm -Rf feeds/luci/modules/!(luci-base)
          rm -Rf feeds/packages/!(lang|libs|devel|utils|net|multimedia)
          rm -Rf feeds/packages/multimedia/!(gstreamer1|ffmpeg)
          rm -Rf feeds/packages/net/!(mosquitto|curl)
          rm -Rf feeds/base/package/firmware
          rm -Rf feeds/base/package/network/!(services|utils)
          rm -Rf feeds/base/package/network/services/!(ppp)
          rm -Rf feeds/base/package/system/!(opkg|ubus|uci|ca-certificates)
          rm -Rf feeds/base/package/kernel/!(cryptodev-linux)
          sed -i '/	refresh_config();/d' scripts/feeds
          
          if [[ "$REPO_URL" == *"kiddin9"* ]]; then
            git clone -b main $REPO_URL packages
            mv packages/* package/
            rm -rf {packages,.github,.gitignore,LICENSE,README.md}
          else
            git clone -b lede $REPO_URL packages 
            mv packages/* package/
            rm -rf {packages,package/golang}
          fi
          
          ./scripts/feeds install ${{ matrix.target }}
          echo "CONFIG_PACKAGE_${{ matrix.target }}=y" >> .config

      - name: 开始编译
        run: |
          cd OpenWrt-$(echo ${{ matrix.arch }} | tr '/' '-')
          make package/${{ matrix.target }}/compile -j$(nproc) V=s

      - name: 上传 ipk
        uses: actions/upload-artifact@v4
        with:
          name: ${{ env.date }}-${{ env.model_name }}-${{ env.arch_path }}-${{ matrix.target }}
          path: OpenWrt-$(echo ${{ matrix.arch }} | tr '/' '-')/bin/packages/*/*/${{ matrix.target }}*.ipk
