name: OpenWrt List Sync
on:
  schedule:
    - cron: '0 3 1 * *'  # 每月1号凌晨3点执行 (UTC时间)
  workflow_dispatch:

jobs:
  sync:
    runs-on: ubuntu-latest
    timeout-minutes: 30
    env:
      MAX_RETRIES: 3
    steps:
      # ------------------------- 初始化阶段 -------------------------
      - name: 检出代码
        uses: actions/checkout@v4
        with:
          fetch-depth: 2  # 启用增量更新所需的历史记录 

      # ------------------------- 数据同步阶段 -------------------------
      - name: 同步官方列表
        run: |
          # 保留原始注释 (方案1要求)
          grep '^#' scripts/Models > models_comments || true
          grep '^#' scripts/Archs > archs_comments || true

          # 从官网抓取最新设备列表 (更新源)
          curl -s https://openwrt.org/supported_devices |
            awk '/<table class="device-list">/,/<\/table>/ {print}' |
            html2text -width 1000 |
            sed -n '/^| Model/,/^$/p' > scripts/Models.new
          
          # 抓取架构列表 (新增版本过滤)
          curl -s https://openwrt.org/architectures |
            grep -Eo '([a-z0-9]+/[a-z0-9_]+)-23.05.3' | # 限定23.05稳定版
            sed 's/-23.05.3//' |
            sort -u > scripts/Archs.new

          # 合并注释与新数据
          cat models_comments scripts/Models.new > scripts/Models
          cat archs_comments scripts/Archs.new > scripts/Archs

      # ------------------------- 校验阶段 ------------------------- 
      - name: 格式校验
        run: |
          # 设备列表正则校验
          if ! grep -qE '^[^:]+:[^:]+' scripts/Models; then
            echo "::error::Models文件格式错误：未找到冒号分隔符"
            exit 1
          fi

          # 架构格式校验
          if grep -qE '[^/]/[^/ ]+' scripts/Archs; then
            echo "::error::Archs文件包含非法架构格式"
            exit 1
          fi

      - name: 兼容性测试
        uses: docker://ghcr.io/openwrt/sdk:x86_64-23.05.3  # 修正镜像源
        with:
          args: |
            # 验证设备-架构映射
            while IFS=: read -r model arch; do
              [[ "$arch" =~ ^# ]] && continue # 跳过注释行
              if ! grep -qxF "$arch" /github/workspace/scripts/Archs; then
                echo "::error::设备 $model 映射到无效架构 $arch"
                exit 1
              fi
            done < /github/workspace/scripts/Models

      # ------------------------- 增量提交阶段 ------------------------- 
      - name: 检测变更
        id: changes
        run: |
          changed_files=$(git diff --ignore-matching-lines='^#' HEAD^ HEAD -- scripts/ | wc -l)
          echo "changed=$([ $changed_files -gt 0 ] && echo 'true' || echo 'false')" >> $GITHUB_OUTPUT

      - name: 提交变更
        if: steps.changes.outputs.changed == 'true'
        uses: stefanzweifel/git-auto-commit-action@v5
        with:
          commit_message: "chore: 同步OpenWrt列表 (增量更新)"
          file_pattern: scripts/
          skip_fetch: true

      # ------------------------- 版本管理阶段 ------------------------- 
      - name: 创建版本快照
        if: steps.changes.outputs.changed == 'true'
        run: |
          current_date=$(date +%Y%m%d)
          git tag sync-$current_date
          git push origin --tags

      - name: 清理旧版本
        run: |
          # 保留最近5个版本 (优化存储)
          git tag -l 'sync-*' --sort=-creatordate | tail -n +6 | xargs -I {} git push origin --delete {}

      - name: 清理工作流日志
        if: always()
        run: |
          gh run delete $(gh run list --workflow=sync.yml --limit 1 --json databaseId -q '.[0].databaseId')
